[FSEC-1600]: Add ec2-instance-ssh-key-attached rule
zendesk/ScoutSuite pull request #43
Opened 2021-06-10 19:16 UTC by Apeksha-M

# Description: Identify and flag if an EC2 instance is launched with an SSH key pair is attached to the instance. Instances should not have keypairs attached except in very specific circumstances.

**Make sure the PR is against the `develop` branch (see [Contributing](https://github.com/nccgroup/ScoutSuite/blob/master/CONTRIBUTING.md)).**

Please include a summary of the change(s) and which issue(s) it addresses. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Select the relevant option(s):

- [X] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (optional)
- [ ] New and existing unit tests pass locally with my changes

2021-06-10 19:22 UTC, eeshaan requested changes
won't this merge delete the DynamoDB rules?

2021-06-10 19:30 UTC, Apeksha-M commented
> won't this merge delete the DynamoDB rules?

Should I be adding the DynamoDB ruleset in this PR?

2021-06-14 15:17 UTC, eeshaan approved these changes

2021-06-14 15:17 UTC, awagneratzendesk approved these changes

2021-06-14 17:02 UTC, merged